### ISSUE TITLE
add binance coin 

### ISSUE THREAD

**Issue by Masoud-garazhian** [MelbourneDeveloper/Ledger.Net#29]
hi everyone 
im tryin to add binance coin (BNB) to the library , and i just keep getting 27012  ledger error,
im using this path "m/44/714/0/0/0"
and im trying to get public key of the token 
CLA = 188 // 0xBC
Ins =  0x01 
the binance app is installed and the ledger is unlocked by pin 

i just dont know what to do to get it running and get public keys ? are there any information about the errors or how to add a token and etc ?! is there an instruction to do add a coin ?!

**Comment by MelbourneDeveloper** [comment]
You can see [here](https://github.com/MelbourneDeveloper/Ledger.Net/blob/40d099dd0a6cc4a6042db86afabe45e18f62edca/src/Ledger.Net/Requests/Concrete/BitcoinAppGetPublicKeyRequest.cs#L3) what a Bitcoin request looks like. You need to do some research on the Ledger dev [website](https://developers.ledger.com/) or talk to the Ledger devs on Slack. They can point you in the right direction.

When you've written the request/response I'll be happy for you to do a PR to add those to the core library.

**Comment by Masoud-garazhian** [comment]
> You can see [here](https://github.com/MelbourneDeveloper/Ledger.Net/blob/40d099dd0a6cc4a6042db86afabe45e18f62edca/src/Ledger.Net/Requests/Concrete/BitcoinAppGetPublicKeyRequest.cs#L3) what a Bitcoin request looks like. You need to do some research on the Ledger dev [website](https://developers.ledger.com/) or talk to the Ledger devs on Slack. They can point you in the right direction.
> 
> When you've written the request/response I'll be happy for you to do a PR to add those to the core library.

thanks for the heads up , I'm looking forward to it

**Comment by MelbourneDeveloper** [comment]
@Masoud-garazhian what happened?

**Comment by Masoud-garazhian** [comment]
> @Masoud-garazhian what happened?

u know, I've decided to use another approach on my task, so I've let it go.
I found a better solution for safe keeping and cold wallets.

and I'm working two jobs, I don't have enough time to contribute. Sorry
